apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-eureka-server
  namespace: shortpingoo
  labels:
    app: {{ .Release.Name }}-eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-eureka-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-eureka-server
    spec:
      containers:
      - name: eureka-server
        image: "565393064007.dkr.ecr.ap-northeast-2.amazonaws.com/eurekaforkubnernetes:latest"
        ports:
        - containerPort: 8088
        env:
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "{{ .Release.Name }}-eureka-server.{{ .Release.Namespace }}.svc.cluster.local"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "false"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "false"
