apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-eureka-server
  namespace: shortpingoo
spec:
  type: ClusterIP
  ports:
  - port: 8088
    targetPort: 8088
  selector:
    app: {{ .Release.Name }}-eureka-server
