apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::565393064007:user/Terraform_msa
      username: argocd_msa
      groups:
        - system:masters