apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://git-codecommit.ap-northeast-2.amazonaws.com/v1/repos/deployment-repo'
    targetRevision: HEAD
    path: helm-charts/frontend   # frontend 차트 경로
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: frontend-dev  # 배포할 Kubernetes 네임스페이스
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
