apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-admin-binding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argocd
    namespace: argocd
roleRef:
  kind: Role
  name: argocd-admin
  apiGroup: rbac.authorization.k8s.io
