# configmap.yaml
# shortpingoo-app 네임스페이스에 있는 애플리케이션이 사용하는 환경 변수 설정입니다.
# 데이터베이스, 서버 설정 등 애플리케이션에서 직접 사용하는 값들을 포함하고 있습니다.
apiVersion: v1
kind: ConfigMap
metadata:
  name: shortpingoo-config
  namespace: shortpingoo-app
data:
  SERVER_PORT: "8080"
  DB_URL: "jdbc:mariadb://users-shoppingoo-database.c7s4augo48pb.ap-northeast-2.rds.amazonaws.com:3306/usersdb"
  DB_USERNAME: "shoppingooadmin"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
  SECURITY_USER_NAME: "admin"
  SECURITY_USER_PASSWORD: "1234"
  ACCESS_TOKEN_PLUS_HOUR: "1"
  REFRESH_TOKEN_PLUS_HOUR: "24"
